# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end


  desc "Run all test for iOS modules"
  lane :run_all_test_ios do
    run_tests(
      scheme: "iOSTests",
      sdk: "iphonesimulator14.2",
      device: "iPhone 8 (14.2)",
      derived_data_path: "./DerivedData",
      clean: true,
    )
  end
end
